# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75397f9de411411921275630fbbca5e2ef6fc9b3f08864f4b47645c6c1e932f0022124aa58cec06ec7fd98bedc2926d3a82a22eaf754778157dcecacdb616887

test:
  secret_key_base: da959cf4f840ed9f964e576ce232f589d886f2ed9abba32a1bfc70e8ac770757254fe23d5a7275ed9c6fd113439d7433cf2587c74f1ac36e90d63e3c46ad63e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
